# ASCP BOC {-}

ASCP BOC's Content Guideline for the Technologist in Microbiology, M(ASCP), and the Specialist in Microbiology, SM(ASCP), certification exams consists of five major content areas. The information below was last revised on ASCP's website Octoboer 2023

## **Preanalytic Procedures** {-}

**Exam Percentage:** M(ASCP): 10% - 15% | SM(ASCP): 5% - 10%

**Description:** Specimen collection and transport, specimen processing, stains (procedure, principle, and interpretation)

## **Analytic Procedures for Bacteriology** {-}

**Exam Percentage:** M(ASCP): 45% - 55% | SM(ASCP): 30% - 40%

**Description:** Specimen sources; colony morphology; agents of infection; normal flora; correlation with other laboratory results; organism pathogenicity; identification methods; antimicrobial susceptibility testing and antibiotic resistance; MRSA/MSSA, VRE, ESBL/CRE screening; BSL-3 pathogens and select agents (bioterrorism)

## **Analytic Procedures for Mycobacteriology, Virology, Parasitology, and Mycology** {-}

**Exam Percentage:** M(ASCP): 20% - 30% | SM(ASCP): 30% - 40%

**Description:** Specimen sources, major pathogens, disease states, identification methods, antimicrobial/antiviral/antifungal susceptibility testing (SM ONLY), serological testing methods

## **Laboratory Operations** {-}

**Exam Percentage:** M(ASCP): 10% - 15% | SM(ASCP): 20% - 25%

**Description:** Postanalytic procedures, quality assessment/troubleshooting, safety, laboratory mathematics, instrumentation, laboratory administration (SM ONLY)