# Reading List {-}

ASCP makes it clear that their suggested reading/reference list for the Technologist in Microbiology, M(ASCP), and the Specialist in Microbiology, SM(ASCP), certification exams "is intended only as a partial reference source". The suggested reading/reference list below was last revised on ASCP's website January 2025

## **Journals** {-}
*   <a href="https://www.sciencedirect.com/journal/clinical-microbiology-newsletter" target="_blank">Clinical Microbiology Newsletter</a>. Published by ScienceDirect.
*   <a href="https://journals.asm.org/journal/cmr" target="_blank">Clinical Microbiology Reviews</a>. Published by American Society for Microbiology.
*   <a href="https://www.sciencedirect.com/journal/diagnostic-microbiology-and-infectious-disease" target="_blank">Diagnostic Microbiology and Infectious Disease</a>. Published by ScienceDirect.
*   <a href="https://journals.asm.org/journal/jcm" target="_blank">Journal of Clinical Microbiology</a>. Published by American Society for Microbiology.
*   <a href="https://www.cdc.gov/mmwr/" target="_blank">Morbidity and Mortality Weekly Report (MMWR)</a>. Published by Centers for Disease Control and Prevention (CDC).


## **Texts** {-}

### **Clinical Microbiology** {-}
*   Carroll, K.C., et al. (Eds.). (2023). <a href="https://www.amazon.com/Manual-Clinical-Microbiology-Multi-Books/dp/1683674294" target="_blank">Manual of Clinical Microbiology</a> (13th ed.). Washington D.C.: ASM Press.
*   De La Maza, L.M. et al. (2020). <a href="https://www.amazon.com/Color-Atlas-Medical-Bacteriology-Books/dp/1683670353" target="_blank">Color Atlas of Medical Bacteriology</a> (3rd ed.). Washington, D.C.: ASM Press.
*   Gilligan, P.H., Shapiro, D.S., & Miller, M.B. (2014). <a href="https://www.amazon.com/Cases-Medical-Microbiology-Infectious-Diseases/dp/1555818684" target="_blank">Cases in Medical Microbiology and Infectious Diseases</a> (4th ed.). Washington, D.C.: ASM Press. (Note: A new edition will be available July 2025)
*   Hata, D.J. & Thomson Jr., R.B. (2016). <a href="https://estore.cap.org/OA_HTML/xxCAPibeCCtpItmDspRte.jsp?section=10043&item=439857&sitex=10020:22372:US" target="_blank">Gram Stain Benchtop Reference Guide</a>. College of American Pathologists.
*   Leber, A.L. & Burnham, C.D. (Eds.). (2023). <a href="https://www.wiley.com/en-us/Clinical+Microbiology+Procedures+Handbook%2C+Multi-Volume%2C+5th+Edition-p-9781683673989" target="_blank">Clinical Microbiology Procedures Handbook</a> (5th ed.). Washington, D.C.: ASM Press.
*   Mahon, C.R. & Lehman, D.C. (2023). <a href="https://www.amazon.com/Textbook-Diagnostic-Microbiology-Connie-M-S-MT/dp/032382997X" target="_blank">Textbook of Diagnostic Microbiology</a> (7th ed.). Elsevier Health Sciences.
*   Procop, G.W., et al. (2016). <a href="https://www.amazon.com/gp/product/1451116594" target="_blank">Koneman’s Color Atlas and Textbook of Diagnostic Microbiology</a> (7th ed.). Jones & Bartlett Learning.
*   Tille, P.M. (2021). <a href="https://www.amazon.com/Bailey-Scotts-Diagnostic-Microbiology-Patricia-dp-0323681050/dp/0323681050" target="_blank">Bailey & Scott’s Diagnostic Microbiology</a> (15th ed.). Elsevier. (Note: A new edition will be available March 2025)

### **Molecular and Immunology** {-}
*   Schmitz, J.L, Detrick, B., & Maurice, R.G.O. (Eds.). (2024). <a href="https://www.amazon.com/Manual-Molecular-Clinical-Laboratory-Immunology/dp/1683673999" target="_blank">Manual of Molecular and Clinical Laboratory Immunology</a> (9th ed.). Washington, D.C.: ASM Press.
*   Persing, D.H. et al. (Eds.). (2016). <a href="https://www.amazon.com/Molecular-Microbiology-Diagnostic-Principles-Practice/dp/1555819087" target="_blank">Molecular Microbiology: Diagnostic Principles and Practice</a> (3rd ed.). Washington D.C.: ASM Press.

### **Parisitology** {-}
*   Ash, L.R. & Orihel, T.C. (2007). <a href="https://www.amazon.com/Atlas-Human-Parasitology-Lawrence-Ash/dp/0891891676" target="_blank">Atlas of Human Parasitology</a> (5th ed.). Chicago: ASCP Press.
*   Garcia, L.S. (2016). <a href="https://www.amazon.com/Diagnostic-Medical-Parasitology-Lynne-Garcia/dp/1555818994" target="_blank">Diagnostic Medical Parasitology</a> (6th ed.). Washington, D.C.: ASM Press.
*   Mathison, B.A. & Pritt, B.S. (2016). <a href="https://estore.cap.org/OA_HTML/xxCAPibeCCtpItmDspRte.jsp?section=10043&item=358857&sitex=10020:22372:US" target="_blank"></a>Arthropod Benchtop Reference Guide. College of American Pathologists. (Note: More appropriate for the Specialist (SM) level)
*   Pritt, B.S. (2014). <a href="https://estore.cap.org/OA_HTML/xxCAPibeCCtpItmDspRte.jsp?section=10043&item=358857&sitex=10020:22372:US" target="_blank">Parasitology Benchtop Reference Guide</a>. College of American Pathologists.

### **Mycology and Virology** {-}
*   Loeffelholz, M.J., et al. (Eds.). (2016). <a href="https://www.amazon.com/Clinical-Virology-Manual-Michael-Loeffelholz/dp/1555819141" target="_blank"></a>Clinical Virology Manual (5th ed.). Washington D.C.: ASM Press.
*   Love, G.L. & Ribes, J.A. (2018). <a href="https://www.amazon.com/COLOR-ATLAS-MYCOLOGY-emeritus-Gordon/dp/B07HJ8FDKB" target="_blank">Color Atlas of Mycology: An Illustrated Field Guide Based on Proficiency Testing</a>. College of American Pathologists.
*   Westblade, L.F., et al., (2023). <a href="https://www.amazon.com/Larones-Medically-Important-Fungi-Identification-dp-1683674405/dp/1683674405" target="_blank">Larone’s Medically Important Fungi: A Guide to Identification</a> (7th ed.). Washington D.C.: ASM Press and John Wiley & Sons, Inc.

### **Laboratory Management** {-}
*   Garcia, L.S., et al. (Eds.). (2024). <a href="https://www.amazon.com/Clinical-Laboratory-Management-ASM-Books-dp-1683673913/dp/1683673913" target="_blank">Clinical Laboratory Management</a> (3rd ed.). Washington D.C.: ASM Press. (Note: More appropriate for the Specialist (SM) level)
*   Harmening, D.M. (2020). <a href="https://www.amazon.com/Laboratory-Management-Principles-Processes-Fourth/dp/0943903181" target="_blank">Laboratory Management: Principles and Processes</a> (4th ed.). St. Petersburg, FL: D.H. Publishing & Consulting Inc. (Note: More appropriate for the Specialist (SM) level)

### **Clinical and Laboratory Standards Institute (CLSI) Publications** {-}
*   Available online at <a href="https://clsi.org/" target="_blank">www.clsi.org</a>



## **Online** {-}
*   <a href="https://onlinelibrary.wiley.com/doi/book/10.1002/9781683670438" target="_blank">ClinMicroNow - American Society of Microbiology (ASM)</a>
*   <a href="https://www.cdc.gov/" target="_blank">Centers for Disease Control and Prevention (CDC)</a>
*   <a href="https://www.cap.org/" target="_blank">College of American Pathologists (CAP)</a>
*   <a href="https://www.cdc.gov/dpdx/" target="_blank">DPDx – CDC’s Division of Parasitic Diseases and Malaria</a>