# Content Areas {-}

Major content areas covered:

## Preanalytic Procedures {-}

*   [Specimen Collection and Transport](collection-transport.html)
*   [Specimen Processing](processing.html)
*   [Stains: Procedure, Principle, and Interpretation](stains.html)

## Analytic Procedures for Bacteriology {-}

*   [Blood and Bone Marrow](blood-bone-marrow.html)
*   [Cerebrospinal Fluid](cerebrospinal-fluid.html)
*   [Body Fluids from Normally Sterile Sites](sterile-sites.html)
*   [Lower Respiratory](lower-respiratory.html)
*   [Upper Respiratory](upper-respiratory.html)
*   [Gastrointestinal](gastrointestinal.html)
*   [Skin, Soft Tissue, and Bone](skin-soft-tissue-bone.html)
*   [Genital Tract](genital-tract.html)
*   [Urine](urine.html)
*   [Identification Methods (Theory, Interpretation, and Application)](identification-methods.html)
*   [Antimicrobial Susceptibility Testing and Antibiotic Resistance](susceptibility-testing-1.html)
*   [MRSA/MSSA, VRE, ESBL/CRE Screening](mrsamssa-vre-esblcre.html)
*   [BSL-3 Pathogens and Select Agents (Bioterrorism)](bsl-3-pathogens.html)

## Analytic Procedures for Mycobacteriology, Virology, Parasitology, and Mycology {-}

*   [Mycobacteriology and Nocardia spp.](procedures.html)
*   [Virology](procedures-1.html)
*   [Parasitology](procedures-2.html)
*   [Mycology](procedures-3.html)
*   [Serology](procedures-4.html)

## Last Updated {-}

Last edit pushed to this site was on <span id="last_updated">`r Sys.Date()`</span>

